trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - '/'

pr:
  branches:
    include:
      - main
  paths:
    include:
      - '/'

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: projPath
    value: '/'
  - name: CredFile
    value: config.ini
  - name: CredFileLibrary
    value: product-readiness.eds_azure.ini
  - name: analysisProject
    value: EDS_Deployment_Azure

jobs:
  - job: Tests
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals Linux
    steps:
      - template: '/miscellaneous/build_templates/config.yml@templates'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)

      - bash: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        displayName: 'Install Azure CLI'

      - bash: |
          chmod +x test.sh
          chmod +x remote.sh
          chmod +x device.sh
          chmod +x reset.sh
          chmod +x reset-device.sh
          ./test.sh
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/
        displayName: 'Run tests'

  - template: '/miscellaneous/build_templates/analysis.yml@templates'
    parameters:
      language: powershell
