trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/'

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - master
    always: true

resources:
  repositories:
  - repository: templates
    type: github
    name: osisoft/OSI-Samples
    endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: projPath
    value: '/'
  - name: CredFile
    value: config.ini
  - name: CredFileLibrary
    value: product-readiness.eds_azure.ini
  - name: analysisProject
    value: EDS_Deployment_Azure

jobs:
  - job: Tests
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: '/miscellaneous/build_templates/config.yml@templates'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)

      - bash: |
          chmod +x test.sh
          chmod +x remote.sh
          chmod +x device.sh
          chmod +x reset.sh
          chmod +x reset-device.sh
          ./test.sh
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/
        displayName: 'Run tests'

  - template: '/miscellaneous/build_templates/analysis.yml@templates'
    parameters:
      language: powershell
